### PR TITLE
Updated to support @react-native-community/async-storage

### PR DESCRIPTION
**Pull request by MohannedElfatih**
Just changed the import to be from @react-native-community to support react-native > 0.60, and added some meta data.

### CODE REVIEW

**Comment by jamonholmgren** [comment]
It would be great to get this merged! +1 from the IR folks, and :wave:

**Comment by skellock** [comment]
Thanks for the PR!

Are any of you fine gentlefolk interested in maintaining this project?

giphy

Halp!

**Comment by jamonholmgren** [comment]
✋ I'll take it, Steve! Considering putting it in Bowser, so I'm invested in making sure it stays fresh and nice-smelling.

**Comment by skellock** [comment]
@jamonholmgren alrighty... i invited you as a maintainer both on [github](https://github.com/skellock/mst-async-storage) and [npm](https://www.npmjs.com/package/mst-async-storage).

Godspeed my friend.

**Pull request merged**
